---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: contactuiappdeployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: contactui
 template:
  metadata:
   name: contactui
   labels:
     app: contactui
  spec:
    containers:
    - name: contactuicontainer
      image: ashokit/contact_ui_ng_app
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: contactuisvc
spec:
  type: LoadBalancer
  selector:
   app: contactui
  ports:
   - port: 80
     targetPort: 80
...
